#!/bin/bash

if ([ $# -lt 3 ]) || ([ $# -eq 1 ] && [ "$1" == "-h" -o "$1" == "--help" ]); then
  echo "디렉토리에 있는 configuration file명을 일괄 변경합니다. "
  echo "ren-config <from service> <to service> <work directory>"
  echo " from service: from service name "
  echo " to service: target servie name "
  echo " work directory: 작업할 디렉토리. 즉, 설정파일들이 있는 디렉토리 "
  echo " ex) ./ren-svc service1 service2 ~/work"
  exit 1
fi

from_svc=$1
to_svc=$2
workdir=$3
fn=""

input=`ls ${workdir}`
for x in $input
do
  if [[ "${x}" =~ ".properties" ]] || [[ "${x}" =~ ".yml" ]]; then
    IFS="/" read -a lists <<< $x
    fn=${lists[ ${#lists[@]}-1 ]}
    if [[ "${fn}" =~ "${from_svc}" ]]; then
      y=`echo ${fn} | sed s/${from_svc}/${to_svc}/g`
      echo "$x => ${workdir}/$y"
      mv $x ${workdir}/$y
    fi
  fi
done
